services:

  gra.dev:
    container_name: gra.dev
    image: gra.dev:latest
    restart: "no"
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      
